- name: Create security group {{ secgroup.name }}
  os_security_group:
    cloud: "{{ cloud }}"
    state: present
    name: "{{ secgroup.name }}"
    description: security group for "{{ secgroup.name }}" servers

- name: Add security group rules to group {{ secgroup.name }}
  os_security_group_rule:
    cloud: "{{ cloud }}"
    state: present
    security_group: "{{ secgroup.name }}"
    protocol: "{{ rule.protocol | default('tcp') }}"
    port_range_min: "{{ rule.port }}"
    port_range_max: "{{ rule.port }}"
    remote_ip_prefix: "{{ rule.ip_prefix | default('0.0.0.0/0') }}"
  loop: "{{ secgroup.rules | default([]) }}"
  loop_control:
    loop_var: rule
    label: "{{ rule.port }}"
